name: "Label issues"
on: pull_request_target
  
jobs:
  label-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.actor != 'srv-rpa-o11y-docs-splunk'
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.teams.getMembershipForUserInOrg({
                org: 'splunk',
                team_slug: 'o11y-docs',
                username: context.payload.sender.login
              });
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['internal']
              })
            } catch (err) {
              return
            }
